### ISSUE TITLE
DynamicFunction

### ISSUE THREAD

**Issue by ib00** [shocker-0x15/GfxExp#4]
What does DynamicFunction class do? Is it an equivalent to a function pointer on a device?

I am interested in using this abstraction (function pointer) for one of my projects.
Is there a simple example of how it's used in a kernel?

Thanks!

**Comment by shocker-0x15** [comment]
This is the abstraction between OptiX's direct callable program and pure CUDA's function pointer since OptiX doesn't allow us to use function pointers.
Note that there seems a performance issue at least in callable programs in the latest driver.
https://forums.developer.nvidia.com/t/performance-regression-in-v510-driver/200914/6

Every sample uses this class (e.g. BSDF evaluation in ReSTIR: per_pixel_ris.cu (pure CUDA) vs optix_restir_rearch_kernels (OptiX))
